name: Tests

on:
  push:
    branches:
      - development
      - "*/head"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda env create -f environment.yaml
          conda activate cs7643-project

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate cs7643-project
          python -m unittest discover tests
